# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animus_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import animus_common_pb2 as animus__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animus_messages.proto',
  package='animus.message',
  syntax='proto3',
  serialized_options=b'\n\036com.cyberselves.animus.messageB\022AnimusMessageProtoH\001Z%github.com/Cyberselves/AnimusMessages\242\002\rAnimusMessage\252\002\016Animus.Message',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x61nimus_messages.proto\x12\x0e\x61nimus.message\x1a\x13\x61nimus_common.proto\"\xe1\x02\n\rAnimusMessage\x12\x10\n\x08SenderID\x18\x01 \x01(\t\x12\x12\n\nReceiverID\x18\x02 \x01(\t\x12\x12\n\nClientType\x18\x03 \x01(\r\x12\x0e\n\x06\x41\x63tion\x18\x04 \x01(\r\x12\x13\n\x0b\x41\x63tionState\x18\x05 \x01(\r\x12\x0f\n\x07Success\x18\x06 \x01(\x08\x12\x0c\n\x04\x44\x61ta\x18\x07 \x01(\x0c\x12\x11\n\tTimestamp\x18\x08 \x01(\x03\x12\x12\n\nFramecount\x18\t \x01(\x03\x12\x0c\n\x04Part\x18\n \x01(\r\x12#\n\x05\x45rror\x18\x0b \x01(\x0b\x32\x14.animus.common.Error\x12\r\n\x05Token\x18\x0c \x01(\t\x12\x14\n\x0c\x43onnectionID\x18\r \x01(\r\x12\x13\n\x0b\x43oreVersion\x18\x0e \x01(\t\x12\x15\n\rClientVersion\x18\x0f \x01(\t\x12\x12\n\nSDKVersion\x18\x10 \x01(\t\x12\x13\n\x0bSDKLanguage\x18\x11 \x01(\t\"\xda\x01\n\x14RegisterRobotMessage\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04Make\x18\x02 \x01(\t\x12\r\n\x05Model\x18\x03 \x01(\t\x12\x0c\n\x04Name\x18\x04 \x01(\t\x12\x0f\n\x07\x44\x65vHash\x18\x05 \x01(\t\x12\x0f\n\x07License\x18\x06 \x01(\t\x12\x16\n\x0eRobotUserEmail\x18\x07 \x01(\t\x12\x15\n\rRobotUserPass\x18\x08 \x01(\t\x12\x15\n\rRobotPairCode\x18\t \x01(\t\x12#\n\x05\x45rror\x18\n \x01(\x0b\x32\x14.animus.common.Error\"\x8c\x01\n\rScannedRobots\x12\x32\n\x0blocalRobots\x18\x01 \x03(\x0b\x32\x1d.animus.message.NetworkRobots\x12#\n\x05\x45rror\x18\x02 \x01(\x0b\x32\x14.animus.common.Error\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"f\n\rNetworkRobots\x12\n\n\x02ID\x18\x01 \x01(\t\x12\n\n\x02IP\x18\x02 \x01(\t\x12\x12\n\nMacAddress\x18\x03 \x01(\t\x12\x0c\n\x04Name\x18\x04 \x01(\t\x12\r\n\x05Model\x18\x05 \x01(\t\x12\x0c\n\x04Make\x18\x06 \x01(\tB~\n\x1e\x63om.cyberselves.animus.messageB\x12\x41nimusMessageProtoH\x01Z%github.com/Cyberselves/AnimusMessages\xa2\x02\rAnimusMessage\xaa\x02\x0e\x41nimus.Messageb\x06proto3'
  ,
  dependencies=[animus__common__pb2.DESCRIPTOR,])




_ANIMUSMESSAGE = _descriptor.Descriptor(
  name='AnimusMessage',
  full_name='animus.message.AnimusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SenderID', full_name='animus.message.AnimusMessage.SenderID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReceiverID', full_name='animus.message.AnimusMessage.ReceiverID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClientType', full_name='animus.message.AnimusMessage.ClientType', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Action', full_name='animus.message.AnimusMessage.Action', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ActionState', full_name='animus.message.AnimusMessage.ActionState', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Success', full_name='animus.message.AnimusMessage.Success', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='animus.message.AnimusMessage.Data', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='animus.message.AnimusMessage.Timestamp', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Framecount', full_name='animus.message.AnimusMessage.Framecount', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Part', full_name='animus.message.AnimusMessage.Part', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='animus.message.AnimusMessage.Error', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Token', full_name='animus.message.AnimusMessage.Token', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ConnectionID', full_name='animus.message.AnimusMessage.ConnectionID', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CoreVersion', full_name='animus.message.AnimusMessage.CoreVersion', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClientVersion', full_name='animus.message.AnimusMessage.ClientVersion', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SDKVersion', full_name='animus.message.AnimusMessage.SDKVersion', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SDKLanguage', full_name='animus.message.AnimusMessage.SDKLanguage', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=416,
)


_REGISTERROBOTMESSAGE = _descriptor.Descriptor(
  name='RegisterRobotMessage',
  full_name='animus.message.RegisterRobotMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='animus.message.RegisterRobotMessage.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Make', full_name='animus.message.RegisterRobotMessage.Make', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Model', full_name='animus.message.RegisterRobotMessage.Model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='animus.message.RegisterRobotMessage.Name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DevHash', full_name='animus.message.RegisterRobotMessage.DevHash', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='License', full_name='animus.message.RegisterRobotMessage.License', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RobotUserEmail', full_name='animus.message.RegisterRobotMessage.RobotUserEmail', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RobotUserPass', full_name='animus.message.RegisterRobotMessage.RobotUserPass', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RobotPairCode', full_name='animus.message.RegisterRobotMessage.RobotPairCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='animus.message.RegisterRobotMessage.Error', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=637,
)


_SCANNEDROBOTS = _descriptor.Descriptor(
  name='ScannedRobots',
  full_name='animus.message.ScannedRobots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='localRobots', full_name='animus.message.ScannedRobots.localRobots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='animus.message.ScannedRobots.Error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='animus.message.ScannedRobots.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='animus.message.ScannedRobots.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=780,
)


_NETWORKROBOTS = _descriptor.Descriptor(
  name='NetworkRobots',
  full_name='animus.message.NetworkRobots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='animus.message.NetworkRobots.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IP', full_name='animus.message.NetworkRobots.IP', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MacAddress', full_name='animus.message.NetworkRobots.MacAddress', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='animus.message.NetworkRobots.Name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Model', full_name='animus.message.NetworkRobots.Model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Make', full_name='animus.message.NetworkRobots.Make', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=782,
  serialized_end=884,
)

_ANIMUSMESSAGE.fields_by_name['Error'].message_type = animus__common__pb2._ERROR
_REGISTERROBOTMESSAGE.fields_by_name['Error'].message_type = animus__common__pb2._ERROR
_SCANNEDROBOTS.fields_by_name['localRobots'].message_type = _NETWORKROBOTS
_SCANNEDROBOTS.fields_by_name['Error'].message_type = animus__common__pb2._ERROR
DESCRIPTOR.message_types_by_name['AnimusMessage'] = _ANIMUSMESSAGE
DESCRIPTOR.message_types_by_name['RegisterRobotMessage'] = _REGISTERROBOTMESSAGE
DESCRIPTOR.message_types_by_name['ScannedRobots'] = _SCANNEDROBOTS
DESCRIPTOR.message_types_by_name['NetworkRobots'] = _NETWORKROBOTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnimusMessage = _reflection.GeneratedProtocolMessageType('AnimusMessage', (_message.Message,), {
  'DESCRIPTOR' : _ANIMUSMESSAGE,
  '__module__' : 'animus_messages_pb2'
  # @@protoc_insertion_point(class_scope:animus.message.AnimusMessage)
  })
_sym_db.RegisterMessage(AnimusMessage)

RegisterRobotMessage = _reflection.GeneratedProtocolMessageType('RegisterRobotMessage', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERROBOTMESSAGE,
  '__module__' : 'animus_messages_pb2'
  # @@protoc_insertion_point(class_scope:animus.message.RegisterRobotMessage)
  })
_sym_db.RegisterMessage(RegisterRobotMessage)

ScannedRobots = _reflection.GeneratedProtocolMessageType('ScannedRobots', (_message.Message,), {
  'DESCRIPTOR' : _SCANNEDROBOTS,
  '__module__' : 'animus_messages_pb2'
  # @@protoc_insertion_point(class_scope:animus.message.ScannedRobots)
  })
_sym_db.RegisterMessage(ScannedRobots)

NetworkRobots = _reflection.GeneratedProtocolMessageType('NetworkRobots', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKROBOTS,
  '__module__' : 'animus_messages_pb2'
  # @@protoc_insertion_point(class_scope:animus.message.NetworkRobots)
  })
_sym_db.RegisterMessage(NetworkRobots)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
