# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animus_companion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import animus_common_pb2 as animus__common__pb2
from . import animus_structs_pb2 as animus__structs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animus_companion.proto',
  package='animus.companion',
  syntax='proto3',
  serialized_options=b'\n com.cyberselves.animus.companionB\024AnimusCompanionProtoH\001Z%github.com/Cyberselves/AnimusMessages\242\002\017AnimusCompanion\252\002\020Animus.Companion',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61nimus_companion.proto\x12\x10\x61nimus.companion\x1a\x13\x61nimus_common.proto\x1a\x14\x61nimus_structs.proto\"\x84\x03\n\rDriverMessage\x12<\n\x06\x41\x63tion\x18\x01 \x01(\x0e\x32,.animus.companion.DriverMessage.DriverAction\x12\x30\n\x0bPerformance\x18\x02 \x03(\x0b\x32\x1b.animus.structs.Performance\x12\x14\n\x0c\x44riverActive\x18\x03 \x01(\x08\x12+\n\x07version\x18\x04 \x01(\x0b\x32\x1a.animus.common.VersionInfo\x12#\n\x05\x45rror\x18\x05 \x01(\x0b\x32\x14.animus.common.Error\x12\n\n\x02IP\x18\x06 \x01(\t\x12\x0c\n\x04port\x18\x07 \x01(\t\"P\n\x0c\x44riverAction\x12\x13\n\x0fGET_PERFORMANCE\x10\x00\x12\x17\n\x13\x43HANGE_DRIVER_STATE\x10\x01\x12\x12\n\x0eINSTALL_UPDATE\x10\x03\"/\n\x0b\x44riverState\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x0b\n\x07RESTART\x10\x02\"\xe3\x01\n\x14InstallDriverMessage\x12\x10\n\x08isUpdate\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07robotID\x18\x04 \x01(\t\x12\x11\n\trobotName\x18\x05 \x01(\t\x12\x11\n\trobotUser\x18\x06 \x01(\t\x12\x15\n\rrobotPassword\x18\x07 \x01(\t\x12\x0f\n\x07robotIP\x18\x08 \x01(\t\x12\x10\n\x08pairCode\x18\t \x01(\t\x12\x14\n\x0cstoreLocally\x18\n \x01(\x08\x12\x0e\n\x06logDir\x18\x0b \x01(\tB\x86\x01\n com.cyberselves.animus.companionB\x14\x41nimusCompanionProtoH\x01Z%github.com/Cyberselves/AnimusMessages\xa2\x02\x0f\x41nimusCompanion\xaa\x02\x10\x41nimus.Companionb\x06proto3'
  ,
  dependencies=[animus__common__pb2.DESCRIPTOR,animus__structs__pb2.DESCRIPTOR,])



_DRIVERMESSAGE_DRIVERACTION = _descriptor.EnumDescriptor(
  name='DriverAction',
  full_name='animus.companion.DriverMessage.DriverAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_PERFORMANCE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHANGE_DRIVER_STATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSTALL_UPDATE', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=347,
  serialized_end=427,
)
_sym_db.RegisterEnumDescriptor(_DRIVERMESSAGE_DRIVERACTION)

_DRIVERMESSAGE_DRIVERSTATE = _descriptor.EnumDescriptor(
  name='DriverState',
  full_name='animus.companion.DriverMessage.DriverState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESTART', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=429,
  serialized_end=476,
)
_sym_db.RegisterEnumDescriptor(_DRIVERMESSAGE_DRIVERSTATE)


_DRIVERMESSAGE = _descriptor.Descriptor(
  name='DriverMessage',
  full_name='animus.companion.DriverMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Action', full_name='animus.companion.DriverMessage.Action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Performance', full_name='animus.companion.DriverMessage.Performance', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DriverActive', full_name='animus.companion.DriverMessage.DriverActive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='animus.companion.DriverMessage.version', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='animus.companion.DriverMessage.Error', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IP', full_name='animus.companion.DriverMessage.IP', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='animus.companion.DriverMessage.port', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRIVERMESSAGE_DRIVERACTION,
    _DRIVERMESSAGE_DRIVERSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=476,
)


_INSTALLDRIVERMESSAGE = _descriptor.Descriptor(
  name='InstallDriverMessage',
  full_name='animus.companion.InstallDriverMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isUpdate', full_name='animus.companion.InstallDriverMessage.isUpdate', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='animus.companion.InstallDriverMessage.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='animus.companion.InstallDriverMessage.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robotID', full_name='animus.companion.InstallDriverMessage.robotID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robotName', full_name='animus.companion.InstallDriverMessage.robotName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robotUser', full_name='animus.companion.InstallDriverMessage.robotUser', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robotPassword', full_name='animus.companion.InstallDriverMessage.robotPassword', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robotIP', full_name='animus.companion.InstallDriverMessage.robotIP', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pairCode', full_name='animus.companion.InstallDriverMessage.pairCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storeLocally', full_name='animus.companion.InstallDriverMessage.storeLocally', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logDir', full_name='animus.companion.InstallDriverMessage.logDir', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=706,
)

_DRIVERMESSAGE.fields_by_name['Action'].enum_type = _DRIVERMESSAGE_DRIVERACTION
_DRIVERMESSAGE.fields_by_name['Performance'].message_type = animus__structs__pb2._PERFORMANCE
_DRIVERMESSAGE.fields_by_name['version'].message_type = animus__common__pb2._VERSIONINFO
_DRIVERMESSAGE.fields_by_name['Error'].message_type = animus__common__pb2._ERROR
_DRIVERMESSAGE_DRIVERACTION.containing_type = _DRIVERMESSAGE
_DRIVERMESSAGE_DRIVERSTATE.containing_type = _DRIVERMESSAGE
DESCRIPTOR.message_types_by_name['DriverMessage'] = _DRIVERMESSAGE
DESCRIPTOR.message_types_by_name['InstallDriverMessage'] = _INSTALLDRIVERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriverMessage = _reflection.GeneratedProtocolMessageType('DriverMessage', (_message.Message,), {
  'DESCRIPTOR' : _DRIVERMESSAGE,
  '__module__' : 'animus_companion_pb2'
  # @@protoc_insertion_point(class_scope:animus.companion.DriverMessage)
  })
_sym_db.RegisterMessage(DriverMessage)

InstallDriverMessage = _reflection.GeneratedProtocolMessageType('InstallDriverMessage', (_message.Message,), {
  'DESCRIPTOR' : _INSTALLDRIVERMESSAGE,
  '__module__' : 'animus_companion_pb2'
  # @@protoc_insertion_point(class_scope:animus.companion.InstallDriverMessage)
  })
_sym_db.RegisterMessage(InstallDriverMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
